### ISSUE TITLE
[FIX] Admin Page Type not working when adding Intern

### ISSUE THREAD

**Issue by yyppsk** [dsaStats/intern-portal#23]
The type field is not updated when clicking on the "Add" Button.
![image](https://github.com/user-attachments/assets/18b2afa8-dc9d-4329-86cb-b9044cc30edf)

**Comment by Anushka-Pote** [comment]
Hey, Is this issue closed now? 
I missed this error earlier actually. Like just inform me about what's the issue or requirement here and I will try to work on it

**Comment by yyppsk** [comment]
> Hey, Is this issue closed now? I missed this error earlier actually. Like just inform me about what's the issue or requirement here and I will try to work on it

It's open for now. You can fix it.
