### ISSUE TITLE
[FEAT] Create Index Page for Admin Dashboard

### ISSUE THREAD

**Issue by Anushka-Pote** [dsaStats/intern-portal#9]
Like I could work on the admin dashboard session particularly-
Header and Footer:
Retain the existing header and footer content from the current page.
Ensure the layout is consistent with the overall design of the application.

Employee and Intern Overview Section:
Create a table to display key information for all employees and interns, including:
Name
Role
Project
Status
The table should initially show a sample list of employees and interns, which you could provide or I can have any randomly 

Add New Employee/Intern Functionality:
Below the table, include an "Add" button that opens a form to input details for a new employee or intern.
The form should have fields for:
Name, Role, Project, Status
Once the form is submitted, the new entry should be dynamically added to the table without refreshing the page.

**Comment by yyppsk** [comment]
Pull a request so that I can review.

**Comment by N-nishita** [comment]
assign this to me.

**Comment by Anushka-Pote** [comment]
@N-nishita There is already an PR open for integration of this Feature I guess. Even I am waiting for that PR's response from Admin side, so we can move with the later features

**Comment by yyppsk** [comment]
Done with the assignment.

**Comment by Anushka-Pote** [comment]
On it, will share the screenshots for the index soon 
Also, can you tag these issues with like hacktoberfest tags?

**Comment by yyppsk** [comment]
I've added it as "Label".

**Comment by Anushka-Pote** [comment]
![image](https://github.com/user-attachments/assets/1864d1bd-935f-4220-b743-63a68bb134cb)
Can you check this out once, if the basic structure matches your requirements? U can inform for few changes, so I can do it before the PR @yyppsk

**Comment by yyppsk** [comment]
That looks just right. However, I gave my team certain a few extra requirements.
![image](https://github.com/user-attachments/assets/3023e428-6d72-4db8-bc44-e378fcf46262)

**Comment by Anushka-Pote** [comment]
I have made the mentioned change you asked me and created the PR.

**Comment by N-nishita** [comment]
May I work on it? I saw @Anushka-Pote  have submitted before me but if you assign me i will also submit

**Comment by yyppsk** [comment]
> May I work on it? I saw @Anushka-Pote have submitted before me but if you assign me I will also submit

I have assigned you. Also, you can work on some issues already opened for the current page.

**Comment by Aryanbhargava18** [comment]
hi @yyppsk i have requested a PR of making the borders of same size and perfectly aligned, signup button visible, solid border added in signup page, please assign it to me.

**Comment by yyppsk** [comment]
> hi @yyppsk i have requested a PR of making the borders of same size and perfectly aligned, signup button visible, solid border added in signup page, please assign it to me.

I've not received it yet.

**Comment by Aryanbhargava18** [comment]
now check
